apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: hello.node1
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-service
                port:
                  number: 80