apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd # <-- NEVER CHANGE
spec:
  project: default
  source:
    repoURL: https://github.com/arslankhanali/GitOps-App-of-Apps-Pattern
    path: apps/argocd/overlays/k3s # <-- CHANGE THIS
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true